### ISSUE TITLE
How to specify the working directory for a project in pmon3?

### ISSUE THREAD

**Issue by BleethNie** [joe-at-startupmedia/pmon3#25]
I want to deploy the application at https://github.com/zhenorzz/goploy to the server and manage it with pmon3, but when I execute the following command, I find that it fails because pmon3 cannot recognize the project's working directory, which results in goploy being unable to read the corresponding configuration file.

```
pmon3 exec /opt/godeploy/goploy 
```

![image](https://github.com/joe-at-startupmedia/pmon3/assets/17614992/61d9f687-4b25-48a3-906e-58248d66c032)

![image](https://github.com/joe-at-startupmedia/pmon3/assets/17614992/cb339f3d-6275-4c00-8333-8d3ee985c29d)

**Comment by ghost** [comment]
I have replicated that Failed message by starting a pmon3 instance without a configuration file specified at `/etc/pmon3/config/apps.config.json`.  This message can be suppressed by providing the following environment variable before the pmon3 command:
```bash
CONFIGOR_SILENT_MODE=1 pmon3 log 1
```

https://github.com/jinzhu/configor/blob/f7a0fc7c9fc697269b1749c1cc472d49baa8d33c/utils.go#L109

While configor did fail to find the non-existent apps config, pmon3 proceeds as usual. As such the output you have provided above should be replicable by issuing the following command: 
```bash
cat /var/log/pmond/1926716e.log
```

Finally any issue you're experiencing with goploy should be unrelated to pmon3.

In the meantime, I will push a commit related to this issue to forego attempting to load an apps config if it doesn't exist.

https://github.com/joe-at-startupmedia/pmon3/blob/5164d437acb4219f46841277a0eb4c1d9df8787b/conf/conf.go#L74

**Comment by ghost** [comment]
That failure message should be suppressed in v1.14.10.

Last, just from taking a quick look at goploy, If you wanted to specify a working directory using pmon3, you would issue the exec command with goploys `--asset-dir` flag as an argument:

```bash
pmon3 exec /opt/godeploy/goploy --args="--asset-dir /opt/godeploy/assets/"
```

I'd use a value of an absolute path to be safe.

**Comment by BleethNie** [comment]
Thank you for your help.
This issue has been resolved.
