### ISSUE TITLE
Processes don't inherit all the user's groups

### ISSUE THREAD

**Issue by cherryroots** [joe-at-startupmedia/pmon3#27]
One of the processes I run needs access to the "render" group for ffmpeg to use vaapi, but the spawned process doesn't include any of the supplementary groups of the user spawning the process.

https://github.com/joe-at-startupmedia/pmon3/blob/c89c7ae0de41baf94ae1d2e9b25d86abda8837f3/pmond/process/executor.go#L34-L37

https://pkg.go.dev/syscall#Credential -> Groups

**Comment by ghost** [comment]
@cherryroots does the commit referenced above resolve the issue?

**Comment by cherryroots** [comment]
Yeah that fixes it, thanks for the quick response
