### ISSUE TITLE
groups

### ISSUE THREAD

**Issue by ghost** [joe-at-startupmedia/pmon3#35]
This will allow the ability to assign processes to groups with m2m cardinality. This will allow executions of applicable commands on the group level.

**Comment by ghost** [comment]
A thread on subcommands: https://github.com/spf13/cobra/issues/1526

**Comment by ghost** [comment]
list of commands which operate on the process level which need to be implemented:
- [x] del
- [x] stop
- [x] restart
- [ ] dgraph?

**Comment by ghost** [comment]
del command operates on the group entity while the drop command operates on the process associated with the group. Because the drop command was implemented it might also be useful to implement the init command.
 - [x] init

**Comment by joe-at-startupmedia** [comment]
Adds groups to desc output:
![Screenshot 2024-09-17 at 22 52 28](https://github.com/user-attachments/assets/d9b42f8f-c0d1-48df-9291-d0f5caa58a68)

**Comment by ghost** [comment]
before init is implemented:
- [x] groups needs to be parsable from the configuration to detect processes which should be associated to a group but have not yet been stored in the database.

Note configuration-based group specific should initially only support inserts because updates would have to detect changes from previous group associations and delete them accordingly. If updates were eventually supported they would need to take the following steps:
1. detect differences in the existing process-group association from the configuration file
2. drop all existing process-group associations for processes specified in the configuration file
3. apply the group insertion and process-group associations

**Comment by ghost** [comment]
Consider storing a Hashset for fast lookups: https://pkg.go.dev/github.com/emirpasic/gods/sets/hashset

This lib is missing a utility to store an integer slice as a hash:

https://forum.golangbridge.org/t/hashcode-for-a-array/6661
https://stackoverflow.com/questions/48272453/what-would-be-a-good-hash-functionor-something-similar-for-an-unique-integer-a

Where an integer slice would probably be a better implementation than a hash map since collisions would be near-impossible.

**Comment by ghost** [comment]
released in 1.16.0.
