### ISSUE TITLE
utilize SO_REUSEPORT to provide cluster mode

### ISSUE THREAD

**Issue by ghost** [joe-at-startupmedia/pmon3#4]
https://douglasmakey.medium.com/socket-sharding-in-linux-example-with-go-b0514d6b5d08

**Comment by ghost** [comment]
https://douglasmakey.medium.com/socket-sharding-in-linux-example-with-go-b0514d6b5d08
https://github.com/wutchzone/zero-downtime-application/blob/master/socket-option-version/main.go

**Comment by joe-at-startupmedia** [comment]
There is no need to do this as applications should be load balancer with more reliable methods instead of at the process level.

**Comment by ghost** [comment]
There is no need to for this as applications should be load-balanced with more reliable methods instead of at the process level.
