### ISSUE TITLE
Web based dashboard

### ISSUE THREAD

**Issue by meshwara** [joe-at-startupmedia/pmon3#49]
Is there a plan to create a web-based dashboard to make management and monitoring easier?

**Comment by ghost** [comment]
At this point, I have no plans to make a web-based dashboard, especially considering I have zero interest with frontend development in its current state (although something using go-wasm would be cool). However, if one were to undertake such a project, the first thing that would be necessary is the development of an API to interface pmond: the deamon serving requests to the pmon3 CLI. Not only would there need to be a pmond-api which would run alongside all pmond instances, but there would also need to be a broker that could communicate with several instances of  pmond-api(s). Based on the project in it's current state (and lack of popularity), I also have no need or interest to develop either of these. My initial intent for developing pmon3 was to extend the lack of features in pmon2 while providing a suitable replacement for memory-hogging pm2 and this purpose have been adequately served for my needs.
